<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="dvcinh6096264" failures="1" tests="3" name="PurchaseOrder" time="7.211" errors="0" timestamp="29 May 2021 12:46:26 GMT">
  <testcase classname="EmployeeTest" name="createEmployee" time="3.996"/>
  <testcase classname="EmployeeTest" name="validateEmployee" time="1.352">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at EmployeeTest.validateEmployee(EmployeeTest.java:126)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- validateEmployee -->
  <testcase classname="EmployeeTest" name="deleteEmployee" time="1.395"/>
</testsuite> <!-- PurchaseOrder -->
